apiVersion: v1
kind: Secret
metadata:
  name: wordpress-demo-secret
  namespace: apps
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: replace-with-long-random-value
  WORDPRESS_DB_PASSWORD: replace-with-long-random-value
---
apiVersion: v1
kind: Secret
metadata:
  name: superset-secret
  namespace: apps
type: Opaque
stringData:
  SUPERSET_SECRET_KEY: replace-with-long-random-value
  SUPERSET_ADMIN_USERNAME: replace-with-admin-username
  SUPERSET_ADMIN_FIRSTNAME: replace-with-admin-first-name
  SUPERSET_ADMIN_LASTNAME: replace-with-admin-last-name
  SUPERSET_ADMIN_EMAIL: replace-with-admin-email
  SUPERSET_ADMIN_PASSWORD: replace-with-long-random-value
---
apiVersion: v1
kind: Secret
metadata:
  name: passbolt-secret
  namespace: apps
type: Opaque
stringData:
  PASSBOLT_DB_PASSWORD: replace-with-long-random-value
---
apiVersion: v1
kind: Secret
metadata:
  name: portainer-secret
  namespace: apps
type: Opaque
stringData:
  PORTAINER_ADMIN_PASSWORD_HASH: "$2y$05$replace-this-with-real-hash"
